### ISSUE TITLE
Using Object Data renders a blank grid

### ISSUE THREAD

**Issue by cheeseytoastie** [key-lime-box/dynamic-table#1]
Following the sample code and the documentation I tried to swap out the sample array for an object,

The grid renders each row but the data is blank - I checked the columns map and tried the sample data from the documentation (only replacing the myData in the sample) and it doesn't work. 

Is there something in the column definition or setup call that needs changing too or is this a bug?

**Comment by ced-b** [comment]
The only changed needed should to add a `field` attribute to each column. This tells it which attribute of the object data to display in each column.

If you did that and it still doesn't work, it would be helpful if you could post some sample code that does not work.

**Comment by cheeseytoastie** [comment]
Totally right - I missed that in the documentation. I did check - honest :) 

Might be worth adding a quick comment above the json example that you need to specify the fields to stop some other idiot doing the same but in fairness it's there under Define Columns! 

Oh - and thanks for a great plugin :100:

**Comment by ced-b** [comment]
Not a problem. I adjusted the sample code for the future.
