### ISSUE TITLE
Json example

### ISSUE THREAD

**Issue by lmarchel13** [key-lime-box/dynamic-table#2]
Hello,

I am trying to fill the table with a json file but it isn't working. The grid renders each row but the data is blank. 

Do you have any sample using JSON? If you do, can you please share with us?

Thank you very much

**Comment by ced-b** [comment]
There is an example using JSON here: https://github.com/key-lime-box/dynamic-table/blob/master/sample/index2.html

If you see rows, but no data is shown in the fields, it might be that you have to specify the `field` property of each column to match the name of the attribute to be shown.

If this does not help. Please post up some sample code of your configuration and data and I can help you out with this.

**Comment by ced-b** [comment]
@lmarchel13 did this help?

**Comment by lmarchel13** [comment]
Sorry for the delay. I was out of office.

It did worked using an AJAX call as below:

```js
var myData = {};
    $.ajax({
        url: "/data.php",
        async: false,
        dataType: 'json',
        success: function(data)
        {
            myData = data;
            
        }
    });
```

Thanks for your support.

**Comment by ced-b** [comment]
Make sure you set the data on the grid from the `success` function:

```js
  // Set-up your grid above

    $.ajax({
        url: "/data.php",
        async: false,
        dataType: 'json',
        success: function(data)
        {
            $("#sample-grid").dynamicTable("data", data, myColumns);
        }
    });
```

Because, of the delay on network traffic, the success function gets called way after the grid is initialized and thus it will not know about the data. When calling it from the success function the grid gets notified of the fact that data is coming in.

Also, make sure your date is actually an array right now you initialize it as an object.

**Comment by lmarchel13** [comment]
Thank you very much. 

Now, I got a different issue. My sort up and sort down feature aren't working anymore. Do you have any idea why?

**Comment by ced-b** [comment]
I can probably help you with that as well. But log that as a new issue as it is a different subject and also see if you can get any errors from the JavaScript console. Also, note which browser and version you are using.

**Comment by lmarchel13** [comment]
Ok, I will do that. Thanks again.
