### ISSUE TITLE
Sort Up and Sort Down issue

### ISSUE THREAD

**Issue by lmarchel13** [key-lime-box/dynamic-table#3]
Hello,

After I've implement the AJAX call to get my data from a SQL Server, the Sort UP and Sort Down aren't working anymore.
I've tried to use this with IE v11.0 and Chrome v59 and both are not showing any console error.

Thanks again for ur support.

**Comment by ced-b** [comment]
I see what you mean. Working out a fix for this and I will let you know shortly.

**Comment by ced-b** [comment]
@lmarchel13 I fixed the sorting. Just grab the latest code and it should work now.

**Comment by lmarchel13** [comment]
@ced-b Now it is working. Thank you again.
