### ISSUE TITLE
Change background color of a cell

### ISSUE THREAD

**Issue by lmarchel13** [key-lime-box/dynamic-table#4]
@ced-b sorry to bother you one more time but I hope this will be the last one.

I am trying to change a cell background color if this cell has a specific text and I am using the code below:

`$("#sample-grid").dynamicTable("data", myData, myColumns);
            $("td:contains('TEXT 1')").addClass('yellowBg');
            $("td:contains('TEXT 2')").addClass('greenBg');
            $("td:contains('TEXT 3')").addClass('redBg');`

and the CSS code:

`.greenBg {
            background-color: green;
            color: green;
         }
         .redBg {
            background-color: red;
            color: red;
         }
         .yellowBg {
            background: yellow;
            color: yellow;
         }`

It is working fine but a have more than 100 rows in this table, and only colors until row 100. Row 101 until the end aren't changing the BG color.
And when I create a filter, any filter, the background returns to the default (white).

Any idea what is it happens?

Thanks again for all your support. Your plugin is amazing and it is helping me a lot!

**Comment by ced-b** [comment]
The reason for this is that the grid does not render all rows in the beginning. That way, if you have a large grid with thousands of rows it loads fast without overloading the browser.

To handle custom styles there is the `cssClass` attribute on every column. See line 50 of the sample doc: https://github.com/key-lime-box/dynamic-table/blob/master/sample/index2.html.

You can put a function which gets passed the value and based on that return a class to be applied to the cell.

**Comment by ced-b** [comment]
Also see [this section](https://github.com/key-lime-box/dynamic-table#2-define-columns) of the documentation. It explains a bit more how the `cssClass` works.

(Btw, if this is helpful, please don't forget to *star* the project in the top right corner and tell your friends. :) )

**Comment by lmarchel13** [comment]
@ced-b thanks again.. now it is working. 

Here is the code for future help for anyone who needs:

`{
                             name       : "Status",
                             field      : "Status",
                             type       : "number",
                             visible    : true,
                             filterType : "list",
                             cssClass   : function (aColumn, aValue, aDisplayValue) {
                                return aValue == "Não Iniciada"  ? "yellowBg" : aValue == "Inic. Real difere do Previsto"  ? "redBg" : aValue == "Inic. Real conforme Previsão"  ? "greenBg" : null
                             },
                             width      : 80
            }`

I will definitely star this plugin. This is amazing and help me a lot. 
Have a nice week :)

**Comment by ced-b** [comment]
Great. I'm glad I could help.
